apiVersion: openinfradev.github.com/v1
kind: HelmValuesTransformer
metadata:
  name: site

global:
  nodeSelector:
    taco-lma: enabled
  clusterName: siim-dev
  storageClassName: rbd
  repository: https://openinfradev.github.io/hanu-helm-repo/
  serviceScrapeInterval: 30s
  defaultPassword: password
  defaultUser: taco
  thanosObjstoreSecret: taco-objstore-secret
  thanosPrimaryCluster: false

charts:
- name: prometheus-operator
  override:
    prometheusOperator.nodeSelector: $(nodeSelector)

- name: eck-operator

- name: prometheus
  override:
    kubeEtcd.endpoints:
    - 192.168.105.161
    - 192.168.105.162
    - 192.168.105.163
    prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName: $(storageClassName)
    prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage: 10Gi
    prometheus.prometheusSpec.retention: 2d
    prometheus.prometheusSpec.externalLabels.taco_cluster: dev
    prometheus.prometheusSpec.nodeSelector: $(nodeSelector)

- name: prometheus-fed-master
  override:
    alertmanager.service.type: NodePort
    alertmanager.service.nodePort: 30111
    alertmanager.alertmanagerSpec.alertmanagerConfigSelector.matchLabels.alertmanagerConfig: example
    alertmanager.alertmanagerSpec.nodeSelector: $(nodeSelector)
    alertmanager.alertmanagerSpec.retention: 2h
    alertmanager.config.global.slack_api_url: https://hooks.slack.com/services/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
    prometheus.prometheusSpec.nodeSelector: $(nodeSelector)
    prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.storageClassName: $(storageClassName)
    prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.spec.resources.requests.storage: 200Gi

- name: prometheus-node-exporter  

- name: kube-state-metrics
  override:
    nodeSelector: $(nodeSelector)

- name: prometheus-pushgateway
  override:
    nodeSelector: $(nodeSelector)

- name: prometheus-process-exporter
  override:
    conf.processes: dockerd,kubelet,kube-proxy,ntpd,node

- name: eck-resource
  override:
    kibana.nodeSelector: $(nodeSelector)
    
    elasticsearch.nodeSets.master.nodeSelector: $(nodeSelector)
    elasticsearch.nodeSets.master.count: 3
    elasticsearch.nodeSets.master.javaOpts: "-Xms2g -Xmx2g"
    elasticsearch.nodeSets.master.limitCpu: 2
    elasticsearch.nodeSets.master.limitMem: 4Gi
    elasticsearch.nodeSets.master.pvc.storageClassName: $(storageClassName)
    elasticsearch.nodeSets.master.pvc.size: 1Gi

    elasticsearch.nodeSets.hotdata.nodeSelector: $(nodeSelector)
    elasticsearch.nodeSets.hotdata.count: 3
    elasticsearch.nodeSets.hotdata.javaOpts: "-Xms10g -Xmx10g"
    elasticsearch.nodeSets.hotdata.limitCpu: 2
    elasticsearch.nodeSets.hotdata.limitMem: 20Gi
    elasticsearch.nodeSets.hotdata.pvc.storageClassName: $(storageClassName)
    elasticsearch.nodeSets.hotdata.pvc.size: 10Gi

    elasticsearch.nodeSets.client.enabled: true
    elasticsearch.nodeSets.client.count: 1
    elasticsearch.nodeSets.client.javaOpts: "-Xms10g -Xmx10g"
    elasticsearch.nodeSets.client.limitCpu: 2
    elasticsearch.nodeSets.client.limitMem: 20Gi
    elasticsearch.nodeSets.client.pvc.storageClassName: $(storageClassName)
    elasticsearch.nodeSets.client.pvc.size: 10Gi

- name: grafana
  override:
    adminPassword: password
    persistence.storageClassName: $(storageClassName)

- name: fluentbit-operator
  override:
    global.base_cluster_url: $(clusterName)
    fluentbitOperator.nodeSelector: $(nodeSelector)
    logExporter.nodeSelector: $(nodeSelector)

- name: fluentbit
  override:
    global.base_cluster_url: $(clusterName)
    global.nodeSelector: $(nodeSelector)
    fluentbit.clusterName: $(clusterName)
    fluentbit.outputs.es.host: eck-elasticsearch-es-http.lma.svc.$(clusterName)
    fluentbit.outputs.kafka:
      enabled: false
    fluentbit.esTemplate.url: https://eck-elasticsearch-es-http.lma.svc.$(clusterName):9200
    fluentbit.nodeSelector: $(nodeSelector)
    fluentbit.targetLogs:
       - bufferChunkSize: 2M
         bufferMaxSize: 5M
         do_not_store_as_default: true
         index: container
         memBufLimit: 20MB
         multi_index:
         - index: platform
           key: $kubernetes['namespace_name']
           value: kube-system|lma|fed|argo|openstack|istio-system|istio-services|trident|registry
         name: dockerlog
         parser: docker
         path: /var/log/containers/*.log
         tag: kube.*
         type: fluent
       - index: syslog
         name: syslog
         parser: syslog-rfc5424
         path: /var/log/syslog
         tag: syslog.*
         type: syslog

- name: addons
  override:
    SPECIAL_VALUE: SPECIAL
    serviceMonitor.trident:
      enabled: false
      interval: $(serviceScrapeInterval)
    serviceMonitor.kubelet.interval: 30s
    serviceMonitor.additionalScrapeConfigs:
    metricbeat.enabled: false
    metricbeat.elasticsearch.host: https://eck-elasticsearch-es-http.lma.svc.$(clusterName):9200
    metricbeat.kibana.host: eck-kibana-dashboard-kb-http.lma.svc.$(clusterName):5601
    metricbeat.prometheus.hosts:
    - fed-master-prometheus.lma.svc.$(clusterName):9090
    # tacoWatcher.host: taco-watcher.lma.svc.$(clusterName)
    # tacoWatcher.joinCluster.body.kibanaUrl: http://eck-kibana-dashboard-kb-http.lma.svc.$(clusterName):5601
    # tacoWatcher.joinCluster.body.grafanaUrl: http://grafana.lma.svc.$(clusterName)
    # tacoWatcher.joinCluster.body.k8sUrl: https://kubernetes.default.svc.$(clusterName)
    kibanaInit.url: http://eck-kibana-dashboard-kb-http.lma.svc.$(clusterName):5601

- name: prometheus-adapter
  override:
    nodeSelector: $(nodeSelector)

- name: kubernetes-event-exporter
  override:
    conf.default.hosts:
    - "https://eck-elasticsearch-es-http.lma.svc.$(clusterName):9200"

- name: thanos
  override:
    global.storageClass: $(storageClassName)
    clusterDomain: $(clusterName)
    existingObjstoreSecret: $(thanosObjstoreSecret)
    query.nodeSelector: $(nodeSelector)
    # query.stores:
    # - thanos-storegateway:9090
    # - thanos-sidecars.lma:30901
    # query.stores:
    # - prometheus-operated.lma.svc.$(clusterName):10901
    query.service:
        type: NodePort
        http:
          port: 9090
          nodePort: 30007
        grpc:
          port: 10901
          nodePort: 30006

    queryFrontend.nodeSelector: $(nodeSelector)
    queryFrontend.service.type: NodePort
    queryFrontend.service.http.nodePort: 30007
    bucketweb.enabled: $(thanosPrimaryCluster)
    bucketweb.nodeSelector: $(nodeSelector)
    compactor.enabled: $(thanosPrimaryCluster)
    compactor.nodeSelector: $(nodeSelector)
    storegateway.nodeSelector: $(nodeSelector)
    compactor.persistence.size: 8Gi
    # compactor.extraFlags:
    # - --compact.enable-vertical-compaction
    # - --deduplication.replica-label="replica"
    storegateway.persistence.size: 8Gi
    ruler.enabled: $(thanosPrimaryCluster)
    ruler.nodeSelector: $(nodeSelector)
    ruler.alertmanagers:
    - http://fed-master-alertmanager.lma.svc.$(clusterName):9093
    ruler.persistence.size: 8Gi
    minio.accessKey.password: $(defaultUser)
    minio.secretKey.password: $(defaultPassword)
    minio.defaultBuckets: thanos
    minio.persistence.storageClass: $(storageClassName)
    minio.persistence.accessMode: ReadWriteOnce
    minio.persistence.size: 10Gi

- name: thanos-config
  override:
    objectStorage:
      bucketName: thanos
      endpoint: thanos-minio.lma.svc.$(clusterName):9000
      access_key: $(defaultUser)
      secret_key: $(defaultPassword)
      secretName: $(thanosObjstoreSecret)
    sidecarsService.name: thanos-sidecars
    sidecarsService.endpoints:
      - 192.168.5.101
